name: card_matching_game
description: A card matching game built with Flutter.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

flutter:
  assets:
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png
    - assets/img5.png
    - assets/img6.png
    - assets/img7.png
    - assets/img8.png
    - assets/back.png
